services:
  icecast:
    deploy:
      replicas: 0
  streamer:
    image: ghcr.io/benjithatfoxguy/spotify-connect-streamer:main
    build: !reset null
    depends_on: []
    ports:
      - "8888:8888"
    environment:
      ICECAST_SOURCE_PASSWORD: "Spotify:91G4rW3G4oIenV"
